version: 1
formatters:
  colored:
    '()': 'colorlog.ColoredFormatter'
    format: '%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
loggers:
  "":
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]