COMMON = {
    #"char": "D", 
    "byte": "unsigned char",
    #"short": "F",
    #"int": "H",
    #"long": "J",
    #"float": "M",
    #"double": "N",
    #"unsigned char": "E",
    "uchar": "unsigned char", "ubyte": "unsigned char",
    #"unsigned short": "G",
    "ushort": "unsigned short",
    # "unsigned int": "I",
    "dword": "unsigned int",
    "uint": "unsigned int",
    #"unsigned long": "K", 
    "DWORD": "unsigned long",
    "ulong": "unsigned long",
    "void": "X",
    "undefined4": "unsigned int",
    "undefined2": "unsigned short",
    "undefined1": "unsigned char",
    "undefined": "unsigned char",
    "pointer": "void *",
    "BOOL": "int",
    #"GUID": "_GUID",
}